<a href="https://colab.research.google.com/github/cjsutton77/PracticeProblems/blob/main/movie_ratings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[![PracticeProbs](https://d33wubrfki0l68.cloudfront.net/b6800cc830e3fd5a3a4c3d9cfb1137e6a4c15c77/ec467/assets/images/transparent-1.png)](https://www.practiceprobs.com/)

# [Movie Ratings](https://www.practiceprobs.com/problemsets/python-numpy/proficient/movie-ratings/)

You’re given a 10x2 array of floats where each row represents a movie. The first column represents the movie’s rating and the second column represents the director’s rating.

In [1]:
import numpy as np

generator = np.random.default_rng(123)
ratings = np.round(generator.uniform(low=0.0, high=10.0, size=(10, 2)))
ratings[[1,2,7,9], [0,0,0,0]] = np.nan

print(ratings)
# [[ 7.  1.]
#  [nan  2.]
#  [nan  8.]
#  [ 9.  3.]
#  [ 8.  9.]
#  [ 5.  2.]
#  [ 8.  2.]
#  [nan  6.]
#  [ 9.  2.]
#  [nan  5.]]

[[ 7.  1.]
 [nan  2.]
 [nan  8.]
 [ 9.  3.]
 [ 8.  9.]
 [ 5.  2.]
 [ 8.  2.]
 [nan  6.]
 [ 9.  2.]
 [nan  5.]]


Create a third column that represents the overall rating. The overall rating is equal to the movie rating if it exists, otherwise the director’s rating.

---

Let's break this one liner into a couple of steps.. 

`np.isnan` checks to see if the element is indeed a nan.  I wasn't able to check doing logical comparison to `np.nan`.  where needs the following arguments:  

condition
if condition is true, 
if condition is false

we reshape since the array is (10,), and it needs to be (10,1).  Once we have it in (10,1) we can just do a `np.hstack` to put the last vector at the end of the matrix.



In [2]:
overall = np.where(np.isnan(ratings[:,0]),ratings[:,1],ratings[:,0])

In [3]:
overall = overall.reshape((10,1))

In [4]:
overall = np.hstack((ratings,overall))
overall

array([[ 7.,  1.,  7.],
       [nan,  2.,  2.],
       [nan,  8.,  8.],
       [ 9.,  3.,  9.],
       [ 8.,  9.,  8.],
       [ 5.,  2.,  5.],
       [ 8.,  2.,  8.],
       [nan,  6.,  6.],
       [ 9.,  2.,  9.],
       [nan,  5.,  5.]])

## [See our solution!](https://www.practiceprobs.com/problemsets/python-numpy/proficient/movie-ratings/solution/)