<a href="https://colab.research.google.com/github/cjsutton77/PracticeProblems/blob/main/vanilla_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[![PracticeProbs](https://d33wubrfki0l68.cloudfront.net/b6800cc830e3fd5a3a4c3d9cfb1137e6a4c15c77/ec467/assets/images/transparent-1.png)](https://www.practiceprobs.com/)

# [Vanilla Neural Network](https://www.practiceprobs.com/problemsets/pytorch/tensors/vanilla-neural-network/)

Here's a "vanilla" 🍦 feed-forward neural network with [logistic activation functions](https://en.wikipedia.org/wiki/Logistic_function) and [softmax](https://en.wikipedia.org/wiki/Softmax_function) applied to the output layer.

<img src="https://www.practiceprobs.com/problemsets/pytorch/images/vanilla.png" width="800px">

Given the following `X` and `y` tensors representing training data,

In [3]:
import torch

# Make data
torch.manual_seed(4321)
X = torch.rand(size=(8,2))
y = torch.randint(low=0, high=3, size=(8,))

print(X)
# tensor([[0.1255, 0.5377],
#         [0.6564, 0.0365],
#         [0.5837, 0.7018],
#         [0.3068, 0.9500],
#         [0.4321, 0.2946],
#         [0.6015, 0.1762],
#         [0.9945, 0.3177],
#         [0.9886, 0.3911]])

print(y) 
# tensor([0, 2, 2, 0, 2, 2, 0, 1])

tensor([[0.1255, 0.5377],
        [0.6564, 0.0365],
        [0.5837, 0.7018],
        [0.3068, 0.9500],
        [0.4321, 0.2946],
        [0.6015, 0.1762],
        [0.9945, 0.3177],
        [0.9886, 0.3911]])
tensor([0, 2, 2, 0, 2, 2, 0, 1])


calculate:

1. the predictions (forward pass)
2. the loss using categorical cross entropy
3. the gradient of the loss with respect to the weights and biases

---

In [4]:
# Your brilliant solution here!

In [12]:
w1 = torch.tensor([[0.48,-0.43],[-0.51,-0.48]])
W1.size()

torch.Size([2, 2])

In [13]:
b1 = torch.tensor([[0.23,0.05]])
b1.size()

torch.Size([1, 2])

In [15]:
w2 = torch.tensor([[-0.99,0.36,-0.75],[-0.66,0.34,0.66]])
w2.size()

torch.Size([2, 3])

In [17]:
b1 = torch.tensor([[0.32,-0.44,0.7]])

In [18]:
b1.size()

torch.Size([1, 3])

In [19]:
def sigmoid(x):
  return 1/(1 + torch.exp(-x))

## [See our solution!](https://www.practiceprobs.com/problemsets/pytorch/tensors/vanilla-neural-network/solution/)